[package]
name = "dexdeck-tui"
description = "Ratatui user interface for DexDeck"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
crossterm.workspace = true
ratatui.workspace = true
thiserror.workspace = true
dexdeck-core = { version = "0.2.0", path = "../dexdeck-core" }
dexdeck-protocol = { version = "0.2.0", path = "../dexdeck-protocol" }

[lints]
workspace = true
